# The URL the site will be built for
base_url = "https://robwalt.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme
theme = "zerm"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
theme_color = "pink"

center = true

author = "Robert Walter"
show_author = true
logo_text = "robWalt.dev"

show_categories = true
show_tags = true

main_menu = [
    {url="/posts/", name = "posts"},
]
